name: ecommerce
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  intl_phone_number_input: ^0.7.3+1
  intl_phone_field: ^3.1.0
  google_fonts: ^4.0.4
  http: ^0.13.6
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.3.1
  geolocator: ^9.0.2
  intl: any
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  image_picker: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
